version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./prisma:/app/prisma
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:./prisma/dev.db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
